version: "2"
services:
  app:
    container_name: blog_test
    image: blog
    build: .
    volumes:
      - .:/app
    links:
      - redis
      - postgres
    ports:
      - 8080:8080
    command: "sh -c 'npm run test'"
  redis:
    image: redis:latest
  postgres:
    image: postgres:latest
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=blog